#!/bin/sh

exec 2>&1

source {{pkg.svc_config_path}}/environment.sh

echo "Testing if pg is ready"
pg_isready -d "${PG_SUPERUSER_URI}" || exit 1

{{#with cfg.postgres}}
echo "Trying to create role '{{username}}'..."

psql -d "${PG_SUPERUSER_URI}" \
  -c "CREATE ROLE \"{{username}}\""

echo "Setting password for role '{{username}}'..."
psql -d "${PG_SUPERUSER_URI}" \
  -c "ALTER ROLE \"{{username}}\" WITH LOGIN PASSWORD '{{password}}'"

echo "Trying to create database '{{dbname}}'..."
PGPASSWORD="${PG_SUPERUSER_PASSWORD}" createdb -U "${PG_SUPERUSER}" -h "${PGHOST}" -p "${PGPORT}" "{{dbname}}"
{{/with}}

# TODO this script is not beautiful -- if the init hook has been run before, this
# will output errors. However, it's quicker to ignore the errors, and `exit 0`
# here, than to first check if the user exists, and not create it if it does, etc
exit 0