#!/bin/sh

set -e
exec 2>&1

{{~#if cfg.proxy}}
exit 0
{{~/if}}

curl="curl -u admin:admin"
prefix=http://127.0.0.1:8000/api/v1

create() {
  request $prefix/$1 -d "$2"
}

link() {
  request $prefix/$1 -XPOST
}

request() {
  status=$($curl -s -o /dev/null -w "%{http_code}" "$@")
  if [[ $status -ne 201 && $status -ne 204 && $status -ne 409 ]]; then
    echo "unexpected response code: $status"
    echo "in call request $@"
  fi
}

# if this returns 401, we're ready
until $(curl -s -o /dev/null -w "%{http_code}\n" $prefix | grep -q 401); do
  echo "waiting for service..."
    sleep 1
done

{{~#each cfg.users as |user|}}
create users '{{toJson user}}'
{{~/each}}

{{~#each cfg.organizations as |org|}}
  {{~#each org.groups as |group|}}
create organizations/{{org.name}}/groups '{{toJson group}}'
  {{~/each}}

  {{~#each org.group_members as |group_member|}}
link organizations/{{org.name}}/groups/{{group_member.group}}/users/{{group_member.user}}
  {{~/each}}

  {{~#each org.policies as |policy|}}
create organizations/{{org.name}}/policies '{{toJson policy}}'
  {{~/each}}

  {{~#each org.group_policies as |group_policy|}}
link organizations/{{org.name}}/groups/{{group_policy.group}}/policies/{{group_policy.policy}}
  {{~/each}}

  {{~#each org.proxy_resources as |proxy_resource|}}
create organizations/{{org.name}}/proxy-resources '{{toJson proxy_resource}}'
  {{~/each}}
{{~/each}}
