sudo: required
dist: xenial

services:
  - docker

language: go

go:
  - 1.9.x

branches:
  only:
    - master

install:
  - make bootstrap

script:
  - make travis

after_success:
  - make bin
  - bash <(curl -s https://codecov.io/bash)
