// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc/user.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc/user.proto

It has these top-level messages:
	User
	AddUserReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id         string                     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ExternalId string                     `protobuf:"bytes,2,opt,name=external_id,json=externalId" json:"external_id,omitempty"`
	Path       string                     `protobuf:"bytes,3,opt,name=path" json:"path,omitempty"`
	Urn        string                     `protobuf:"bytes,4,opt,name=urn" json:"urn,omitempty"`
	Created    *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=created" json:"created,omitempty"`
	Updated    *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=updated" json:"updated,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *User) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *User) GetUrn() string {
	if m != nil {
		return m.Urn
	}
	return ""
}

func (m *User) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *User) GetUpdated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Updated
	}
	return nil
}

type AddUserReq struct {
	ExternalId string `protobuf:"bytes,1,opt,name=external_id,json=externalId" json:"external_id,omitempty"`
	Path       string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
}

func (m *AddUserReq) Reset()                    { *m = AddUserReq{} }
func (m *AddUserReq) String() string            { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()               {}
func (*AddUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddUserReq) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *AddUserReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "grpc.User")
	proto.RegisterType((*AddUserReq)(nil), "grpc.AddUserReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	AddUser(ctx context.Context, in *AddUserReq, opts ...grpc1.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc1.ClientConn
}

func NewUserServiceClient(cc *grpc1.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc1.CallOption) (*User, error) {
	out := new(User)
	err := grpc1.Invoke(ctx, "/grpc.UserService/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	AddUser(context.Context, *AddUserReq) (*User, error)
}

func RegisterUserServiceServer(s *grpc1.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc/user.proto",
}

func init() { proto.RegisterFile("grpc/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x49, 0x1a, 0x5a, 0x71, 0x91, 0xa0, 0xf2, 0x14, 0x65, 0x49, 0xc9, 0x54, 0x16, 0x5b,
	0x2a, 0x0c, 0xac, 0x65, 0x63, 0x0d, 0x65, 0x61, 0x41, 0x49, 0x7c, 0x4d, 0x2d, 0x92, 0x38, 0xf8,
	0x0f, 0xe2, 0x2b, 0xf2, 0xad, 0x90, 0x9d, 0x46, 0x95, 0x90, 0x50, 0xb7, 0xf3, 0xef, 0xde, 0xb3,
	0xdf, 0x33, 0xdc, 0x34, 0x6a, 0xa8, 0x99, 0xd5, 0xa8, 0xe8, 0xa0, 0xa4, 0x91, 0x24, 0x72, 0x20,
	0xcd, 0x1a, 0x29, 0x9b, 0x16, 0x99, 0x67, 0x95, 0xdd, 0x33, 0x23, 0x3a, 0xd4, 0xa6, 0xec, 0x86,
	0x51, 0x96, 0xff, 0x04, 0x10, 0xbd, 0x6a, 0x54, 0xe4, 0x1a, 0x42, 0xc1, 0x93, 0x60, 0x15, 0xac,
	0xaf, 0x8a, 0x50, 0x70, 0x92, 0x41, 0x8c, 0xdf, 0x06, 0x55, 0x5f, 0xb6, 0xef, 0x82, 0x27, 0xa1,
	0x5f, 0xc0, 0x84, 0x9e, 0x39, 0x21, 0x10, 0x0d, 0xa5, 0x39, 0x24, 0x33, 0xbf, 0xf1, 0x33, 0x59,
	0xc2, 0xcc, 0xaa, 0x3e, 0x89, 0x3c, 0x72, 0x23, 0x79, 0x80, 0x45, 0xad, 0xb0, 0x34, 0xc8, 0x93,
	0xcb, 0x55, 0xb0, 0x8e, 0x37, 0x29, 0x1d, 0x23, 0xd1, 0x29, 0x12, 0xdd, 0x4d, 0x91, 0x8a, 0x49,
	0xea, 0x5c, 0x76, 0xe0, 0xde, 0x35, 0x3f, 0xef, 0x3a, 0x4a, 0xf3, 0x2d, 0xc0, 0x96, 0x73, 0xd7,
	0xa6, 0xc0, 0xcf, 0xbf, 0x05, 0x82, 0x7f, 0x0b, 0x84, 0xa7, 0x02, 0x9b, 0x47, 0x88, 0x9d, 0xff,
	0x05, 0xd5, 0x97, 0xa8, 0x91, 0xdc, 0xc1, 0xe2, 0x78, 0x23, 0x59, 0x52, 0xf7, 0xa1, 0xf4, 0xf4,
	0x40, 0x0a, 0x23, 0x71, 0xc7, 0xfc, 0xe2, 0xe9, 0xf6, 0x2d, 0x6b, 0x84, 0x39, 0xd8, 0x8a, 0xd6,
	0xb2, 0x63, 0x3b, 0xac, 0xb5, 0xd0, 0x25, 0xdb, 0x4b, 0xdb, 0x7e, 0xc8, 0x9e, 0x39, 0x65, 0x35,
	0xf7, 0xe1, 0xef, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc3, 0xfb, 0xe0, 0x1e, 0xac, 0x01, 0x00,
	0x00,
}
